# Generated by Django 4.2.7 on 2024-01-31 08:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('store', '0002_cartmod'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartmod',
            name='qty',
            field=models.IntegerField(default=1),
        ),
        migrations.CreateModel(
            name='ordermod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_order', models.DateField(auto_now_add=True)),
                ('order_status', models.BooleanField(default='pending', null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('order_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.productmod')),
            ],
        ),
    ]
