# Generated by Django 4.2.7 on 2024-01-31 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_alter_cartmod_qty_ordermod'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordermod',
            name='address',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='ordermod',
            name='price',
            field=models.IntegerField(null=True),
        ),
    ]
